name: Publish Python SDK

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: startsWith(github.event.release.tag_name, 'kadoa-python-sdk-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: bun install

      - name: Generate SDK code
        run: bun kadoa-codegen generate -c python

      - name: Install build tooling
        working-directory: sdks/python
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        working-directory: sdks/python
        run: |
          python -m build

      - name: Publish to PyPI
        working-directory: sdks/python
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/* --non-interactive
