name: Publish Node SDK

on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'node-sdk-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install

      - name: Generate SDK code
        run: bun kadoa-codegen generate -c node

      - name: Build Node SDK
        working-directory: sdks/node
        run: bun run build

      - name: Publish to npm
        working-directory: sdks/node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm whoami || npm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          npm publish --access public
